apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: "v1.19.x"
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    extraArgs:
      - --feature-gates=ExperimentalGatewayAPISupport=true
    serviceAccount:
      create: true
      name: cert-manager
      annotations:
        azure.workload.identity/client-id: "${CERT_MANAGER_CLIENT_ID}"
