apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "2.0.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 10m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      name: external-secrets
      annotations:
        azure.workload.identity/client-id: "${ESO_CLIENT_ID}"
